### ISSUE TITLE
Unable to Complete download

### ISSUE THREAD

**Issue by keven-mate** [samloader/samloader#66]
## Description
I'm unable to complete the download of firmwares, I've tried more than three times but it eventually stops on around 33%.
Somethimes it just stops with no error messages, and sometimes it says 'connection rejected reset by peer', my internet connection is working fine and I did not disconnect from it, it happens even when using USB tethering, I don't have an RG45 cable to test the download with it.

Here's an image: https://imgur.com/a/OWPeTYL

## Reproduction Steps
samloader -m SM-G960F -r XFA download -v G960FXXUHFVB4/G960FOXMHFVB4/G960FXXUHFVB4/G960FXXUHFVB4 -O .

## Output
Traceback (most recent call last):
  File "/home/cypher/.local/bin/samloader", line 33, in <module>
    sys.exit(load_entry_point('samloader==0.4', 'console_scripts', 'samloader')())
  File "/home/cypher/.local/lib/python3.10/site-packages/samloader/main.py", line 50, in main
    for chunk in r.iter_content(chunk_size=0x10000):
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 763, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))

## Environment
OS: Artix Linux
Kernel: 5.15.34-1-lts
Python: 3.10.4

**Comment by keven-mate** [comment]
It was an issue with my router, I switched it and I was able to complete the downloads with no interruption.
