### ISSUE TITLE
getlogiccheck input too short

### ISSUE THREAD

**Issue by sanderlegit** [samloader/samloader#69]
## Description
Trying to download firmware causes error

## Reproduction Steps
samloader -m SM-G960F -r PHN download -v G960FXXUHFVB4 -o output

## Output
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/conda_tf/bin/samloader", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/Caskroom/miniforge/base/envs/conda_tf/lib/python3.9/site-packages/samloader/main.py", line 37, in main
    path, filename, size = getbinaryfile(client, args.fw_ver, args.dev_model, args.dev_region)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/conda_tf/lib/python3.9/site-packages/samloader/main.py", line 85, in getbinaryfile
    req = request.binaryinform(fw, model, region, client.nonce)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/conda_tf/lib/python3.9/site-packages/samloader/request.py", line 42, in binaryinform
    "LOGIC_CHECK": getlogiccheck(fwv, nonce)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/conda_tf/lib/python3.9/site-packages/samloader/request.py", line 11, in getlogiccheck
    raise Exception("getlogiccheck() input too short")
Exception: getlogiccheck() input too short

## Environment
Macos monteray 12.2.1 (21D62)
Conda 4.12.0
Python 3.9.12

aside from that, there are 4 firmware versions listed. im trying to flash an S9 with heimdall. how do i tell which firmware version i want?
e.g. G960FXXUHFVB4/G960FOXMHFVB4/G960FXXUHFVB4/G960FXXUHFVB4

**Comment by sanderlegit** [comment]
nvm, found another issue with the same. need to pass complete firmware string.

Thanks for the tool !
